In [1]:
import numpy as np
import pandas as pd
import random as random
import sys

sys.getrecursionlimit()

sys.setrecursionlimit(1000000)

# solve for 3

In [2]:
#assumed that sudoku is in numpy array
def check_in_col(col,grid,num):
    return num in grid[:,col]
def check_in_row(row,grid,num):
    return num in grid[row]
def check_in_square(row,col,grid,num):
    if row<3:
        if col<3:
            return num in grid[:3,:3]
        elif col<6:
            return num in grid[:3,3:6]
        else: 
            return num in grid[:3,6:9]
    elif row<6:
        if col<3:
            return num in grid[3:6,:3]
        elif col<6:
            return num in grid[3:6,3:6]
        else: 
            return num in grid[3:6,6:9]
    else:
        if col<3:
            return num in grid[6:9,:3]
        elif col<6:
            return num in grid[6:9,3:6]
        else: 
            return num in grid[6:9,6:9]

In [3]:
def isgridfull(grid,size):
    for i in range(size):
        if 0 in grid[i]:
            return False
    return True

In [4]:
def printgrid(grid):
    for i in range(9):
        print(grid[i],end = '\n')
    print(' ')

In [5]:
counter=1
def solve_sudoku1(grid):
    global counter
    for i in range(0,81):
        if i==80:
            if grid[8][8]:
                return True
        row=i//9
        col=i%9
        if grid[row][col]==0:
            for num in range(1,10):
                if (not check_in_col(col,grid,num)) and (not check_in_row(row,grid,num)) and (not check_in_square(row,col,grid,num)):
                    grid[row][col]=num
                    if solve_sudoku(grid):
                        return True
                if num==9:
                    grid[row][col]=0 
            break
    return False
def solve_sudoku(grid):
    global counter
    for i in range(0,81):
        if i==80:
            if grid[8][8]:
                return True
        row=i//9
        col=i%9
        if grid[row][col]==0:
            numbers = list(range(1,10))
            random.shuffle(numbers)
            for idx,num in enumerate(numbers):
                if (not check_in_col(col,grid,num)) and (not check_in_row(row,grid,num)) and (not check_in_square(row,col,grid,num)):
                    grid[row][col]=num
                    if solve_sudoku(grid):
                        return True
                if idx==8:
                    grid[row][col]=0 
            break
    return False

In [6]:
grid = np.array([[3,0,0,6,8,0,0,9,0],[6,0,0,0,0,2,8,1,0],[0,0,0,0,9,5,3,0,7],[4,0,0,0,0,8,0,0,2],[0,0,5,2,0,3,7,0,0],[1,0,0,4,0,0,0,0,3],[9,0,4,8,7,0,0,0,0],[0,1,6,5,0,0,0,0,8],[0,8,0,0,3,1,0,0,6]])

In [7]:
printgrid(grid)

[3 0 0 6 8 0 0 9 0]
[6 0 0 0 0 2 8 1 0]
[0 0 0 0 9 5 3 0 7]
[4 0 0 0 0 8 0 0 2]
[0 0 5 2 0 3 7 0 0]
[1 0 0 4 0 0 0 0 3]
[9 0 4 8 7 0 0 0 0]
[0 1 6 5 0 0 0 0 8]
[0 8 0 0 3 1 0 0 6]
 


In [8]:
solve_sudoku1(grid)

True

In [9]:
grid

array([[3, 5, 1, 6, 8, 7, 2, 9, 4],
       [6, 7, 9, 3, 4, 2, 8, 1, 5],
       [2, 4, 8, 1, 9, 5, 3, 6, 7],
       [4, 9, 3, 7, 6, 8, 1, 5, 2],
       [8, 6, 5, 2, 1, 3, 7, 4, 9],
       [1, 2, 7, 4, 5, 9, 6, 8, 3],
       [9, 3, 4, 8, 7, 6, 5, 2, 1],
       [7, 1, 6, 5, 2, 4, 9, 3, 8],
       [5, 8, 2, 9, 3, 1, 4, 7, 6]])

In [10]:
%%time
for _ in range(100):
    grid = np.array([[3, 0, 6, 5, 0, 8, 4, 0, 0],[5, 2, 0, 0, 0, 0, 0, 0, 0],[0, 8, 7, 0, 0, 0, 0, 3, 1],[0, 0, 3, 0, 1, 0, 0, 8, 0],
                     [9, 0, 0, 8, 6, 3, 0, 0, 5],[0, 5, 0, 0, 9, 0, 6, 0, 0],[1, 3, 0, 0, 0, 0, 2, 5, 0],[0, 0, 0, 0, 0, 0, 0, 7, 4],
                     [0, 0, 5, 2, 0, 6, 3, 0, 0]])
    solve_sudoku1(grid)

Wall time: 12.1 s


# creating grids

In [11]:
def fillsmallgrid(grid,start,siz):
    numbers = np.array(range(1,siz**2+1))
    random.shuffle(numbers)
    grid[start:start+siz,start:start+siz] = np.reshape(numbers,(siz,siz))
    
def creategrid(siz = 3):
    size = siz**2
    grid = np.zeros((size,size),dtype = int)
    i = 0
    while i<siz:
        fillsmallgrid(grid,i*siz,siz)
        i+=1
    solve_sudoku(grid)
    return grid

In [13]:
creategrid()

array([[2, 6, 8, 7, 5, 3, 9, 4, 1],
       [9, 5, 4, 8, 1, 2, 6, 7, 3],
       [7, 3, 1, 6, 9, 4, 8, 2, 5],
       [1, 8, 7, 4, 3, 5, 2, 6, 9],
       [5, 9, 2, 1, 7, 6, 3, 8, 4],
       [3, 4, 6, 2, 8, 9, 1, 5, 7],
       [6, 2, 9, 5, 4, 1, 7, 3, 8],
       [8, 1, 5, 3, 6, 7, 4, 9, 2],
       [4, 7, 3, 9, 2, 8, 5, 1, 6]])

# solve sudoku for block size = n (general, not 3)

In [278]:
#assumed that sudoku is in numpy array format
def check_in_col(col,grid,num):
    return num in grid[:,col]
def check_in_row(row,grid,num):
    return num in grid[row]
def check_in_square(row,col,grid,siz,num):
    fr = 1
    fc = 1
    rsq = 0
    csq = 0
    while fr:
        rsq+=1
        if row<rsq*siz:
            fr = 0
    while fc:
        csq+=1
        if col<csq*siz:
            fc = 0
    return num in grid[(rsq-1)*siz:rsq*siz,(csq-1)*siz:csq*siz]

In [282]:
def isgridfull(grid,size=9):
    #size is side of whole sudoku
    for i in range(size):
        if 0 in grid[i]:
            return False
    return True

In [280]:
def printgrid(grid,size=9):
    for i in range(size):
        print(grid[i],end = '\n')
    print(' ')

In [283]:
counter=1

def solve_sudoku(grid,size = 9,siz=3):
#     print(grid)
#     size = len(grid)
#     siz = math.sqrt(size)
#     if siz%1:
#         print('sudoku is of wrong size. length of each side should be a perfect square')
#         return
        
    global counter
    tot_nums = size**2
    for i in range(0,tot_nums):
        if i==tot_nums-1:
            if grid[size-1][size-1]:
                return True
        row=i//size
        col=i%size
        if grid[row][col]==0:
            numbers = list(range(1,size+1))
            random.shuffle(numbers)
            for idx,num in enumerate(numbers):
                if (not check_in_col(col,grid,num)) and (not check_in_row(row,grid,num)) and (not check_in_square(row,col,grid,siz,num)):
                    grid[row][col]=num
#                     counter+=1
                    if solve_sudoku(grid,size,siz):
                        return True
                if idx==size-1:
                    grid[row][col]=0 
            break
    return False

In [284]:
grid = np.array([[3,0,0,6,8,0,0,9,0],[6,0,0,0,0,2,8,1,0],[0,0,0,0,9,5,3,0,7],[4,0,0,0,0,8,0,0,2],[0,0,5,2,0,3,7,0,0],[1,0,0,4,0,0,0,0,3],[9,0,4,8,7,0,0,0,0],[0,1,6,5,0,0,0,0,8],[0,8,0,0,3,1,0,0,6]])

In [285]:
printgrid(grid)

[3 0 0 6 8 0 0 9 0]
[6 0 0 0 0 2 8 1 0]
[0 0 0 0 9 5 3 0 7]
[4 0 0 0 0 8 0 0 2]
[0 0 5 2 0 3 7 0 0]
[1 0 0 4 0 0 0 0 3]
[9 0 4 8 7 0 0 0 0]
[0 1 6 5 0 0 0 0 8]
[0 8 0 0 3 1 0 0 6]
 


In [286]:
solve_sudoku(grid)

True

In [287]:
grid

array([[3, 5, 1, 6, 8, 7, 2, 9, 4],
       [6, 7, 9, 3, 4, 2, 8, 1, 5],
       [2, 4, 8, 1, 9, 5, 3, 6, 7],
       [4, 9, 3, 7, 6, 8, 1, 5, 2],
       [8, 6, 5, 2, 1, 3, 7, 4, 9],
       [1, 2, 7, 4, 5, 9, 6, 8, 3],
       [9, 3, 4, 8, 7, 6, 5, 2, 1],
       [7, 1, 6, 5, 2, 4, 9, 3, 8],
       [5, 8, 2, 9, 3, 1, 4, 7, 6]])

In [308]:
def fillsmallgrid(grid,start,siz):
    numbers = np.array(range(1,siz**2+1))
    random.shuffle(numbers)
    grid[start:start+siz,start:start+siz] = np.reshape(numbers,(siz,siz))
    
def creategrid(siz = 3):
    #this wouldn't work for siz<3. because then the diagonal blocks are not independent.
#     Try and check for 2. sometimes you can get full sudoku if you are lucky. else just diagonal blocks filled
    size = siz**2
    grid = np.zeros((size,size),dtype = int)
    i = 0
    while i<siz:
        fillsmallgrid(grid,i*siz,siz)
        i+=1
    solve_sudoku(grid,size,siz)
    return grid

In [310]:
%%time
creategrid(2)

Wall time: 959 µs


array([[1, 2, 0, 0],
       [4, 3, 0, 0],
       [0, 0, 3, 1],
       [0, 0, 4, 2]])

In [301]:
%%time
creategrid(3)

Wall time: 28.3 ms


array([[1, 5, 3, 9, 7, 6, 2, 8, 4],
       [2, 8, 6, 1, 5, 4, 9, 3, 7],
       [7, 9, 4, 3, 2, 8, 6, 1, 5],
       [9, 6, 7, 2, 3, 5, 8, 4, 1],
       [5, 4, 8, 6, 9, 1, 3, 7, 2],
       [3, 2, 1, 8, 4, 7, 5, 6, 9],
       [6, 3, 9, 7, 1, 2, 4, 5, 8],
       [4, 7, 2, 5, 8, 3, 1, 9, 6],
       [8, 1, 5, 4, 6, 9, 7, 2, 3]])

In [292]:
%%time
creategrid(4)

Wall time: 1.05 s


array([[ 7, 12,  1, 13, 15,  5, 11,  3, 14, 10, 16,  2,  4,  9,  6,  8],
       [ 5,  9, 16,  4,  7,  6, 12,  8, 13, 11,  3, 15, 10,  1,  2, 14],
       [11, 15, 10,  2,  1, 13, 14, 16,  8,  6,  4,  9,  7,  3,  5, 12],
       [ 3, 14,  6,  8,  2,  9,  4, 10,  1,  5,  7, 12, 13, 11, 15, 16],
       [ 1,  6,  2,  7, 10,  8, 13,  5,  9, 12, 14, 16, 11, 15,  3,  4],
       [ 9, 10, 13,  3, 12, 11,  2,  7, 15,  8,  6,  4, 16, 14,  1,  5],
       [12,  8,  4,  5, 14, 15, 16,  9,  2,  3,  1, 11,  6, 13,  7, 10],
       [16, 11, 15, 14,  3,  4,  1,  6,  5,  7, 10, 13,  8,  2, 12,  9],
       [ 2, 16, 12,  9,  6,  3, 10, 13,  7,  1, 11, 14,  5,  4,  8, 15],
       [ 4,  5,  7,  6,  9, 16,  8,  1, 12, 13, 15,  3,  2, 10, 14, 11],
       [ 8,  1, 14, 11,  5, 12, 15,  4, 10,  2,  9,  6,  3, 16, 13,  7],
       [10, 13,  3, 15, 11,  2,  7, 14, 16,  4,  8,  5, 12,  6,  9,  1],
       [ 6,  7,  5,  1, 13, 14,  3, 15,  4, 16, 12, 10,  9,  8, 11,  2],
       [15,  4, 11, 16,  8,  1,  6,  2,  3,  9,  5,

In [293]:
%%time
creategrid(5)

Wall time: 10min 6s


array([[ 5,  9, 15, 19, 17, 14, 22, 20,  6, 13, 23, 16,  2, 11, 24, 21,
         1,  3,  8, 18,  7,  4, 12, 10, 25],
       [11, 20, 22, 24,  3,  8, 17,  1,  2, 16, 21, 25,  7, 15,  5, 12,
         4, 14, 13, 10, 23,  9, 19, 18,  6],
       [14, 12, 13, 10, 25,  4, 19,  7, 15, 11,  3,  1,  9, 17, 18,  6,
         2, 16, 23, 24, 21,  8, 20, 22,  5],
       [ 2, 23, 21,  4,  1,  9, 10, 18, 24, 12, 13, 19, 20,  8,  6,  7,
        22, 25, 15,  5, 11, 14, 17,  3, 16],
       [18,  6,  8,  7, 16, 21, 23, 25,  5,  3,  4, 10, 22, 12, 14, 19,
         9, 20, 11, 17,  2, 13, 24, 15,  1],
       [25, 13, 18,  1, 10,  7,  2, 14, 22, 23,  9, 15, 16, 20, 11,  4,
        19, 12,  5,  3,  6, 17,  8, 21, 24],
       [23, 16, 12,  3, 14, 24, 21,  8,  9,  5,  7,  6, 13,  2, 17, 15,
        20, 10, 18, 25, 22,  1, 11,  4, 19],
       [24, 17,  5, 22, 11, 13,  3, 16,  1, 20, 14, 21, 12, 19,  4,  9,
         8, 23,  7,  6, 15, 18, 10, 25,  2],
       [15,  8, 20,  6, 19, 17, 18, 12,  4, 10, 24,  5, 25,  3, 

In [296]:
4**(128)

115792089237316195423570985008687907853269984665640564039457584007913129639936

In [297]:
5**(320)

46816763546921983271558494138586765699150233387941833163371554538603832766739996494866350975392646334430537906314200196391753374199149312046122692338075289270907454151724452290906351194232914991744110011495649814605712890625